# Generated by Django 4.1 on 2022-09-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCandidat', '0003_rename_rendez_vous_day_candidat_rendez_vous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='rendez_vous',
        ),
        migrations.AddField(
            model_name='recruteur',
            name='crenaux_proposé',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
